# Generated by Django 5.2.3 on 2025-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_alter_reportcard_date_report_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
